name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: golangci-lint (default)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github-token: ${{ secrets.github_token }}
          golangci-lint-flags: "./testdata"

  govet:
    name: govet
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: govet
        uses: reviewdog/action-golangci-lint@v1
        with:
          github-token: ${{ secrets.github_token }}
          golangci-lint-flags: "--disable-all -E govet ./testdata"
          tool-name: govet

  golint:
    name: golint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github-token: ${{ secrets.github_token }}
          golangci-lint-flags: "--disable-all -E golint ./testdata"
          tool-name: golint
          level: warning

  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-golangci-lint@v1
        with:
          github-token: ${{ secrets.github_token }}
          golangci-lint-flags: "--disable-all -E misspell ./testdata"
          tool-name: misspell
          level: info
